<a href="https://colab.research.google.com/github/ElCorn66/TensorFlow_Study/blob/main/Tensors_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar 


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])

In [ ]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10, 7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10., 7.],
                             [3., 2],
                             [8., 9.],dtype=float16]) 
another_matrix

SyntaxError: ignored

In [ ]:
tensor = tf.constant([[[1,2,3,],
                       ]])

In [ ]:
# tf.Variable()
changeable_tensor = tf.Variable([10, 7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
# creating random tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# 17.Shuffling the order of tensors
# shuffle your data
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
not_shuffled = tf.random.set_seed(101)
not_shuffled          